### ISSUE TITLE
Как успехи?

### ISSUE THREAD

**Issue by best-tech** [EvilBeaver/OneScript.Web#1]

**Comment by EvilBeaver** [comment]
Глухо. Совсем нет сил разобраться с .NET Core, т.к. он изменяется быстрее, чем я успеваю про него читать.

**Comment by EvilBeaver** [comment]
обновление

https://www.facebook.com/ovsiankin.aa/posts/992963864175889

**Comment by best-tech** [comment]
Как бы пнуть что бы быстро и далеко летело)))

**Comment by EvilBeaver** [comment]
https://infostart.ru/public/722160/
