### ISSUE TITLE
question: Asp.Net какой версии ?

### ISSUE THREAD

**Issue by allustin** [EvilBeaver/OneScript.Web#22]
работаю над аутентификацией и тут мне nuGet показывает что версия макета App.Net у нас 1.1.2 - а актуальная 2.0.3 и вышла 2.1.preview

Вопрос у нас какая версия то ?

https://github.com/EvilBeaver/OneScript.Web/blob/master/src/OneScript/OneScriptWeb.csproj#L34

**Comment by allustin** [comment]
ответ получен - докер файл тут https://github.com/EvilBeaver/oscript-infrastructure/blob/master/docker/Dockerfile.mono

**Comment by allustin** [comment]
@EvilBeaver а про asp.net скажешь чего-нибудь ? Почему 1.1 ?

**Comment by EvilBeaver** [comment]
На момент создания проекта 2.0, ЕМНИП, была в статусе беты
