### ISSUE TITLE
Ошибка подключения компонент

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript.Web#38]
в ScriptEngine.HostedScript:
```c#
        public void AttachAddIn(string dllPath)
        {
            var assembly = System.Reflection.Assembly.LoadFrom(dllPath);
            EngineInstance.AttachAssembly(assembly, EngineInstance.Environment); // <-- смотрим сюда
        }
```
EngineInstance объявлен как `internal ScriptingEngine EngineInstance{ get; set; }` и устанавливается только при создании `HostedScriptEngine`. В случае веб-движка это свойство остаётся null и ПодключитьВнешнююКомпоненту падает с NullReferenceException.

**Comment by EvilBeaver** [comment]
в веб-движке не используется HostedScriptEngine вовсе. В какой момент сюда попадает исполнение?

**Comment by dmpas** [comment]
Дык, вестимо, при вызове ПодключитьВнешнююКомпоненту в `package-loader.os` какой-нибудь библиотеки вроде sql или ftp.
