### ISSUE TITLE
Ошибка "Connection already open" при открытом соединении DbConnection

### ISSUE THREAD

**Issue by otymko** [EvilBeaver/OneScript.Web#58]
В созданном соединении с информационной базой PostgreSQL, при выполнении запрос: ExecuteCommand() Или QueryResult() вылетает ошибка "Connection already open":
![image](https://user-images.githubusercontent.com/11651847/58974874-bf6b7400-87ed-11e9-9088-4689fe226fe1.png)

Нужно проверять, открыто ли соединение.

**Comment by EvilBeaver** [comment]
Дайте код на 1С который приводит к данной ошибке? В какой момент выполнения кода 1С это происходит?

**Comment by otymko** [comment]
Используем в appconfig.json базу postgresql. После запуска main.os в коде вызываем:
```bsl
Соединение = Новый ИнформационнаяБаза;
Запрос = Соединение.НовыйЗапрос();
Запрос.Текст = "SELECT * FROM Авторы"; // уже создана таблица с именем Авторы
РезультатЗапроса = Запрос.Выполнить();
// или
Запрос.ВыполнитьКоманду();
```
Движок выкидывает исключение:
![image](https://user-images.githubusercontent.com/11651847/58998647-fe201f00-882b-11e9-8752-c03251fe3a65.png)

P.S. Пример выше это упрощенный пример. Все соединение производятся через entity
