### ISSUE TITLE
Не собирается под docker-compose под Ubuntu 18.04

### ISSUE THREAD

**Issue by stilet** [EvilBeaver/OneScript.Web#60]
При сборке проекта вываливается на шаге:
Step 7/11 : ADD ${binaries} $BINPREFIX/
ERROR: Service 'engine' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder643363036/artifact/net461/debian-x64: no such file or directory
Я так понимаю - нет собранного бинарника в image omvc-engine-developer

**Comment by nixel2007** [comment]
Добрый день. Собираете мастер или девелоп? Если мастер, то попробуйте собрать файл из девелоп-ветки

**Comment by stilet** [comment]
да, из мастера. Завтра попробую

**Comment by stilet** [comment]
нет девелоп тоже не собирается - пишет:
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
ERROR: Service 'engine' failed to build: The command '/bin/sh -c dotnet restore' returned a non-zero code: 1

**Comment by stilet** [comment]
на 4м шаге падает
Step 4/16 : RUN dotnet restore
 ---> Running in 564a14034c14

**Comment by EvilBeaver** [comment]
Попробуйте готовый образ взять из докер-хаба evilbeaver/oscript-web

по неработающему Compose понятно, посмотрим, что там. Спасибо за инфу
