### ISSUE TITLE
Реализовать методы для работы 1connector

### ISSUE THREAD

**Issue by k2589** [EvilBeaver/OneScript.Web#72]
Библиотека 1connector не хочет работать в osweb, так-как не реализованы следующие методы:

- ПолучитьHexСтрокуИзДвоичныхДанных()
 
- ТекущаяУниверсальнаяДата()

Если их добавить, то библиотека будет работать) 

Что касается  ТекущаяУниверсальнаяДата() - она спокойно заменяется на ТекущаяДата(), а вот с ПолучитьHexСтрокуИзДвоичныхДанных() - функции использующие его приходится убирать.

**Comment by nixel2007** [comment]
Для второй функции, насколько я понимаю, достаточно сделать публикацию вот тут:

https://github.com/EvilBeaver/OneScript.Web/blob/master/src/OneScript/Application/WebGlobalContext.cs#L53

@EvilBeaver для первой там же?

**Comment by EvilBeaver** [comment]
Да, это там
