### ISSUE TITLE
Асинхронное выполнение кода

### ISSUE THREAD

**Issue by zeratulayuris** [EvilBeaver/OneScript.Web#74]
Не хватает async/await. Вероятно, это к движку, но более актуально именно в веб - для тех же опросов нескольких сервисов одновременно.
В движке есть возможность использовать СоздатьПроцесс() для запуска произвольных команд и можно было бы выкрутиться, создав несколько процессов и в цикле проверяя их завершение. Но у такого способа ограничения: неудобно передавать параметры/получать результат, необходимость ставить консольный движок оскрипта в контейнер с приложением.

Насколько сложно (и нужно) запилить такое в osweb?

**Comment by EvilBeaver** [comment]
async/await не поддерживается на уровне виртуальной машины 1Скрипта.

wontfix
