### ISSUE TITLE
Подключение внешних компонент в .net core

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript.Web#84]
Компоненты, собранные под большой движок, не могут быть использованы в OS.Web, который на основе .net core, потому что .net core требует разрешение зависимостей с требованием НЕ МЛАДШЕ.
Таким образом, компонента, собранная с зависимостью от более свежего движка, не сможет работать в освеб, в котором более старый движок, даже если возможности нового движка не используются.

Предлагается для разрешения зависимостей при загрузке сборок ОСкрипта отключить проверку на версию  и выдавать в качестве результата ту сборку, которая есть в ОС.вебе.

**Comment by EvilBeaver** [comment]
Удалил сабмодуль, с ним масса проблем, включая непонятные расхождения в исходниках на дженкисе. Перевел на нугет

**Comment by dmpas** [comment]
Я вот всё думаю, вкорячивать костыль или нет. Если мы при выпуске движка будем тут же обновлять и освеб, то проблемы быть и не должно. А если в компоненте завязался на одну версию, а освеб используешь старый, то наверное ССЗБ: снижай зависимость или обновляй освеб.

**Comment by EvilBeaver** [comment]
я думаю количество компонент в библиотеке позволяет нам сделать так, как нам удобно
