### ISSUE TITLE
Инструкция для контрибьютора & Win10 & Rider

### ISSUE THREAD

**Issue by ilyabaztard** [EvilBeaver/OneScript.Web#93]
Помогите разобраться новичку.

Исходные данные: Windows 10
Установил JetBrains Rider 2021.3.2
File - Open - Get from version control
Build solution
Результат: виндовые бинарники в папке .\src\OneScript\bin\Release\netcoreapp3.1
OneScript.WebHost.exe запускается, работает

В инструкция для контрибьютора написано: _выполните команду publish solution в вашей IDE_
Я не нахожу такой команды. В контекстном меню солюшена нахожу только "Publish...". Жму. Получаю меню с вариантами: IIS, Local folder
IIS-а у меня нет, выбираю Local folder. Результат: виндовые бинарники в папке .\src\OneScript\bin\Release\netcoreapp3.1\publish

Далее _в корне репозитория выполните команду docker-compose build - в списке ваших образов появится образ docker omvc-engine-developer на базе официального образа mono:5.10_
```
docker-compose build
Building engine
[+] Building 3.9s (8/8) FINISHED
```
Образ omvc-engine-developer появился
```
docker run --rm -v C:/Data/oscript/esb-web:/app -p 5000:5000 omvc-engine-developer
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/var/osp.net/OneScript.WebHost": stat /var/osp.net/OneScript.WebHost: no such file or directory: unknown.
```

Правильно ли я понимаю, что для сборки контейнеров нужны таки линуксовые бинарники? Как их собрать?

В файле docker-compose.yml написано
```
engine:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    image: omvc-engine-developer
```
т.е. image omvc-engine-developer создается на основе Dockerfile
в котором в свою очередь написано
`FROM mcr.microsoft.com/dotnet/core/aspnet:3.1`
Почему в инструкции написано, что образ docker omvc-engine-developer на базе официального образа mono:5.10?? Где тут mono?

docker-compose.yml: `context: ./src`
Dockerfile: `COPY . /var/osp.net`
В папку /var/osp.net скопируются все исходники из папки src? Так там вроде бинарники должны оказаться, потому как `ENTRYPOINT ["/var/osp.net/OneScript.WebHost"]`

Я запутался напрочь. Помогите разобраться что есть что и как собрать и протестировать проект.
И как потом собрать image по образу и подобию evilbeaver/oscript-web

**Comment by EvilBeaver** [comment]
Попробуйте просто без IDE сделать dotnet publish -o <папка-куда-публиковать>

**Comment by ilyabaztard** [comment]
> Документация могла и устареть. Где вы читаете "инструкцию контрибьютора"?

Заглавный README.md
```
Контрибьютору
ознакомьтесь с руководством контрибьютора
```

**Comment by ilyabaztard** [comment]
> Попробуйте просто без IDE сделать dotnet publish -o <папка-куда-публиковать>

Результат тот же. В папке есть файл OneScript.WebHost.exe (что есть виндовые бинарники?)
но нет файла OneScript.WebHost (что есть линуксовые бинарники?)
```
PS C:\Data\RiderProjects\OneScript.Web\src
> C:\Users\i.kuznetsov\.dotnet\dotnet.exe publish -o c:\temp\dn

Вас приветствует .NET 6.0!
---------------------
Версия пакета SDK: 6.0.100

Телеметрия
---------
Средства .NET собирают данные об использовании для повышения удобства. Данные собираются корпорацией Майкрософт и предоставляются сообществу. Вы можете отключить отправку данных телеметрии, установив значение "1" или "true" для переменной среды DOTNET_CLI_TELEMETRY_OPTOUT в подходящей оболочке.

Дополнительные сведения о сборе данных телеметрии средствами CLI .NET см. на странице https://aka.ms/dotnet-cli-telemetry.

----------------
Установлен сертификат разработки HTTPS в ASP.NET Core.
Чтобы сделать сертификат доверенным, выполните команду "dotnet dev-certs https --trust" (только в Windows и macOS).
Дополнительные сведения об HTTPS: https://aka.ms/dotnet-https
----------------
Как написать свое первое приложение: https://aka.ms/dotnet-hello-world
Узнать о новых возможностях: https://aka.ms/dotnet-whats-new
Просмотреть документацию: https://aka.ms/dotnet-docs
Сообщить о проблемах и найти исходный код на GitHub: https://github.com/dotnet/core
Для просмотра доступных команд введите команду "dotnet --help" или посетите следующую страницу: https://aka.ms/dotnet-cli.
--------------------------------------------------------------------------------------
Microsoft (R) Build Engine версии 17.0.0+c9eb9dd64 для .NET
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Определение проектов для восстановления...
  Восстановлен C:\Data\RiderProjects\OneScript.Web\src\OneScriptWeb.Tests\OneScriptWeb.Tests.csproj (за 997 ms).
  Восстановлен C:\Data\RiderProjects\OneScript.Web\src\OneScript\OneScriptWeb.csproj (за 1,79 sec).
  Восстановлен C:\Data\RiderProjects\OneScript.Web\src\OneScriptWeb.Tests\OneScriptWeb.Tests.csproj (за 12,99 sec).
C:\Data\RiderProjects\OneScript.Web\src\OneScript\BackgroundJobs\CronWrapper.cs(27,26): warning CS0618: "Cron.DayInterval(int)" является устаревшим: 'Please use Cron expressions instead. Will be removed in 2.0.0' [C:\Data\RiderProjects\OneScript.Web\src\OneScript\OneScriptWeb.csproj]
C:\Data\RiderProjects\OneScript.Web\src\OneScript\BackgroundJobs\CronWrapper.cs(39,26): warning CS0618: "Cron.HourInterval(int)" является устаревшим: 'Please use Cron expressions instead. Will be removed in 2.0.0' [C:\Data\RiderProjects\OneScript.Web\src\OneScript\OneScriptWeb.csproj]
C:\Data\RiderProjects\OneScript.Web\src\OneScript\BackgroundJobs\CronWrapper.cs(51,26): warning CS0618: "Cron.MinuteInterval(int)" является устаревшим: 'Please use Cron expressions instead. Will be removed in 2.0.0' [C:\Data\RiderProjects\OneScript.Web\src\OneScript\OneScriptWeb.csproj]
  OneScriptWeb -> C:\Data\RiderProjects\OneScript.Web\src\OneScript\bin\Debug\netcoreapp3.1\OneScript.WebHost.dll
  OneScriptWeb -> c:\temp\dn\
C:\Data\RiderProjects\OneScript.Web\src\OneScriptWeb.Tests\HttpRequestResponseTests.cs(146,13): warning CS0618: "ObsoleteMockExtensions.SetupSet<T, TProperty>(Mock<T>, Expression<Func<T, TProperty>>)" является устаревшим: 'Replaced by SetupSet(Action)' [C:\Data\RiderProjects\OneScript.Web\src\OneScriptWeb.Tests\OneScriptWeb.Tests.csproj]
  OneScriptWeb.Tests -> C:\Data\RiderProjects\OneScript.Web\src\OneScriptWeb.Tests\bin\Debug\netcoreapp3.1\OneScriptWeb.Tests.dll
  OneScriptWeb.Tests -> c:\temp\dn\
```

**Comment by ilyabaztard** [comment]
Получить бинарники линукса помогло
`dotnet publish -o <папка-куда-публиковать> --runtime linux-x64`
Далее манипуляции с бинарниками и Dockerfile выдали корректный докер контейнер по образцу evilbeaver/oscript-web

Инструкцию контрибьютора надо бы обновить/сделать более вменяемой

**Comment by nixel2007** [comment]
> Инструкцию контрибьютора надо бы обновить/сделать более вменяемой

Сделайте! :)
